### ISSUE TITLE
Hinzufügen eines externen Repos führt zur Exception

### ISSUE THREAD

**Issue by HandBreit** [swt14w01/JRMDS#1]
Hab eine Xml aus dem Github jqassistant hinzufügen wollen, da warf es mir ne Exception

**Comment by HandBreit** [comment]
Nicht reproduzierbar, eventuell vorm Mergen getestet?

**Comment by poisonnuke** [comment]
reproduzierbar, wenn man eine für uns nicht gültige Datei wie diese hier:
https://github.com/buschmais/jqassistant-demo/blob/master/jqassistant/demo.xml

hinzufügt, kommt es in der Tiefensuche zu einem Fehler, weil die referenzierten Objekte fehlen. Daher muss eine Fehlermeldung gebracht werden, dass diese XML unvollständig ist.

**Comment by poisonnuke** [comment]
wurde wohl schon gefixed, es kommt nun eine Fehlermeldung, kann nun keine Exception mehr reproduzieren
