### ISSUE TITLE
Validation errors for rule references shall be rendered in the same form

### ISSUE THREAD

**Issue by DirkMahler** [swt14w01/JRMDS#12]
If the validation of referenced rules fail (e.g. cycle or a concept referencing a constraint) a new page is rendered containing an error message.
Under the aspect of usability it would be preferable that
- the error(s) would be presented in the same form
- adding even would not be possible for invalid data

**Comment by poisonnuke** [comment]
concept/constraint issue solved

performance impact for showing cycles on the fly is much to high and renders interface useless.
