### ISSUE TITLE
update severity exception

### ISSUE THREAD

**Issue by HandBreit** [swt14w01/JRMDS#17]
ich habe versucht: testpro -> fastcheck -> severity ändern -> update severity 
wirft ne exception:
org.springframework.web.bind.MissingServletRequestParameterException: Required String[] parameter 'toUpdateOverride' is not present at org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.handleMissingValue(RequestParamMethodArgumentResolver.java:253) at ...

By override checkbox aktiv geht das updaten, dann ist aber ne checkbox aktiv ohne anklicken.

**Comment by poisonnuke** [comment]
da hast du irgendeine nicht aktuelle Version verwendet. Denn in der aktuellen Version hättest du nichtmal etwas bei der Gruppe ändern können, da dein Login geprüft wird und per Default aktuell noch keiner sich als Projektleiter eintragen kann.

Ich kann das Problem nicht reproduzieren.
