### ISSUE TITLE
XML-Converter throws String error while opening project

### ISSUE THREAD

**Issue by poisonnuke** [swt14w01/JRMDS#18]
while trying to download the project over xml, the following error occurs:

String index out of range: -1 java.lang.StringIndexOutOfBoundsException: String index out of range: -1 at java.lang.String.substring(Unknown Source) at 
jrmds.xml.XmlLogic.getAllProjectComponents(XmlLogic.java:274) at 
jrmds.xml.XmlController.objectsToXML(XmlController.java:59) at

**Comment by HandBreit** [comment]
Bitte nochmal versuchen, müsste gefixt sein

**Comment by poisonnuke** [comment]
looks good
