### ISSUE TITLE
Bereitstellen eines Projektes als Übergruppe

### ISSUE THREAD

**Issue by HandBreit** [swt14w01/JRMDS#2]
Das wäre sowohl zur Backup- Lösung als auch zum Zusammenführen von internen Projekt mit externen Regeln nötig, dass ich das ganze Projekt auch übergeben bekomme.

**Comment by poisonnuke** [comment]
ist an sich erstmal nicht gefordert, daher noch nicht implementiert. Können wir aber gern machen, ich überleg mir mal ein spezielles Gruppenobjekt, anhand dessen das unterschieden werden kann.

**Comment by poisonnuke** [comment]
ist ja bereits implementiert
