### ISSUE TITLE
Download als XML  - Button auf Projekt/Gruppe/...?

### ISSUE THREAD

**Issue by HandBreit** [swt14w01/JRMDS#3]
Diese Exportfunktion ist glaube ich noch nicht umgesetzt oder?

**Comment by poisonnuke** [comment]
schreib mal den genauen Link zum Aufrufen hier rein, das Einfügen ist dann schnell gemacht.

**Comment by HandBreit** [comment]
@RequestMapping(value = "/xml/{project}/{refId}", method = RequestMethod.GET)

Die refId ist die der Gruppe und wäre optional. Ohne den Parameter wird das gesamte Projekt in einer XML-Datei zusammen gefasst.

**Comment by edisontrent1337** [comment]
closed #3.
